replicaCount: 2 # final value TBD

image:
  pullSecrets: dollarshaveclub-kubernetes-pull-secret

ingress:
  enabled: false # TBD
  hosts:
    - avro-schema-registry.shave.io # TBD
  annotations:
    kubernetes.io/ingress.class: fastly-production # TBD

app:
  env: production
  fingerprintVersion: 2
  disableSchemaRegistration: true
  statsdHost: datadog.tools.svc.cluster.local.
  vaultAddr: http://vault.shave.io:8200
  vaultRole: avro-schema-registry-production
  vaultK8sAuthUrlPrefix: kube.shave.io
  vaultTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
  vaultPathPrefix: secret/services/avro-schema-registry/production/
  rollbarAccessToken: d8034ca2eef844e0a1df3fc1927b2a83
  ddTraceAnalyticsEnabled: true
