apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-{{ randAlphaNum 5 | lower }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      name:  {{ template "fullname" . }}
      labels:
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "rake", "db:setup"]
          env:
            - name: RACK_ENV
              value: {{ .Values.app.env | quote }}
            - name: RAILS_ENV
              value: {{ .Values.app.railsEnv | quote }}
            - name: RAILS_LOG_TO_STDOUT
              value: {{ .Values.app.railsLogToStdOut | quote }}
{{- if .Values.app.dbURL }}
            - name: DATABASE_URL
              value: {{ .Values.app.dbURL | quote }}
{{- else }}
            - name: DB_USER
              value: {{ .Values.app.dbUser | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.app.dbPassword | quote }}
            - name: DB_HOST
              value: {{ .Values.app.dbHost | quote }}
            - name: DB_PORT
              value: {{ .Values.app.dbPort | quote }}
{{- end }}
{{- if .Values.app.statsdHost }}
            - name: STATSD_HOST
              value: {{ .Values.app.statsdHost | quote }}
            - name: STATSD_PORT
              value: {{ .Values.app.statsdPort | quote }}
{{- end }}
