# Default values for avro-schema-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/dollarshaveclub/avro-schema-registry
  tag: master
  pullPolicy: Always
  pullSecrets: quay-key

nameOverride: ""
fullnameOverride: ""

service:
  name: avro-schema-registry
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000

ingress:
  enabled: false
  hosts:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: schemaregistry.example.local
      paths: []

dnsPolicy: ClusterFirst
dnsConfig: {}
#  options:
#    - name: ndots
#      value: '2'
#    - name: attempts
#      value: '5'
#    - name: timeout
#      value: '1'

app:
  env: development
  railsEnv: development
  railsLogToStdOut: true
  fingerprintVersion: all
  disableSchemaRegistration: false
  vaultAddr: http://vault:8200
  vaultRole: ''
  vaultK8sAuthUrlPrefix: kubernetes
  vaultTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
  vaultPathPrefix: secret/services/avro-schema-registry/

livenessProbe:
  initialDelaySeconds: 300
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  httpGet:
    path: '/' #TBD

readinessProbe:
  initialDelaySeconds: 20
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  httpGet:
    path: '/' #TBD

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
