apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
{{- if  .Values.envoy.enabled }}
      name: {{ .Values.envoy.name }}
      targetPort: {{ .Values.envoy.internalProxyPort }}
      protocol: TCP
{{- else }}
      name: {{ .Chart.Name }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
{{- end }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "name" . }}
