name: Reusable workflow for Build and Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      ecr:
        required: true
        description: "Aws account string for the ECR"
        default: 932427637498.dkr.ecr.us-west-2.amazonaws.com
        type: string
      ecr_repo_name:
        required: true
        description: "Name of the ECR repo "
        type: string
      dockerfile:
        required: false
        description: "Path to Dockerfile"
        type: string
      chart_path:
        required: false
        description: "Path to helm charts"
        type: string
      release_name:
        required: false
        description: "Helm release name"
        type: string
      namespace:
        required: false
        description: "Kubernetes namespace name"
        type: string
      release_path:
        required: false
        description: "Path to release file"
        type: string
      runner:
        description: 'The runner to use for this job'
        required: true
        type: string
        default: 'arc-runner-63'

jobs:
  build:
    uses: dollarshaveclub/dsc-github-actions/.github/workflows/build.yml@main
    with:
      ecr: ${{ inputs.ecr }}
      ecr_repo_name: ${{ inputs.ecr_repo_name }}
      dockerfile: ${{ inputs.dockerfile }}
    secrets:
     AWS_ECR_ACCESS_KEY_TEST: ${{ secrets.AWS_ECR_ACCESS }}
     AWS_ECR_ACCESS_SECRET_TEST: ${{ secrets.AWS_ECR_SECRET }}
  Deploy:
    needs: build
    uses: dollarshaveclub/dsc-github-actions/.github/workflows/build-deploy.yml@main
    with:
      ecr: ${{ inputs.ecr }}
      ecr_repo_name: ${{ inputs.ecr_repo_name }}
      chart_path: ${{ inputs.chart_path }}
      release_name: ${{ inputs.release_name }}
      namespace: ${{ inputs.namespace }}
      release_path: ${{ inputs.release_path }}
      runner: ${{ inputs.runner }}
    secrets:
      AWS_ECR_ACCESS_KEY_TEST: ${{ secrets.AWS_ECR_ACCESS }}
      AWS_ECR_ACCESS_SECRET_TEST: ${{ secrets.AWS_ECR_SECRET }}
      KUBECONFIG_63: ${{ secrets.KUBECONFIG_63 }}
      KUBECONFIG_APPLE: ${{ secrets.KUBECONFIG_APPLE }}